@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{ "make": "Ford", "model": "Focus" }

###
@newCar = {{postACar.response.body._id}}

###
# POST 
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "make": "Ford", "model": "Focus" }

###
GET {{endpoint}} HTTP/1.1
content-type: application/json

###
GET {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json

###
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json

{ "model": "Fiesta" }

###
DELETE {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json

###
DELETE {{endpoint}}/123 HTTP/1.1
content-type: application/json