@endpoint = http://localhost:3000/api/v1/cars

###
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "make": "Toyota", "model": "Corolla" }

###
GET {{endpoint}} HTTP/1.1
content-type: application/json

###
GET {{endpoint}}/6ab57c59eb148622a2c35dc1 HTTP/1.1
content-type: application/json

###
PUT {{endpoint}}/6ab57c59eb148622a2c35dc1 HTTP/1.1
content-type: application/json

{ "model": "Yaris" }

###
DELETE {{endpoint}}/6ab57c59eb148622a2c35dc1 HTTP/1.1
content-type: application/json